### PR TITLE
Extended OpenStack APIs (esp. a Glance API)

### PR DESCRIPTION
**Pull request by mpeuster**
This is work done to integrate son-emu with OpenSource MANO (OSM) by using the project groups OpenStack APIs. 

Therefore I tweaked some minor things and added additional endpoints OSM wants to have.

(also contains some other upstream changes: a quick and dirty dashboard for demos that polls the emulator's REST api)

### CODE REVIEW

**Comment by mpeuster** [comment]
Any idea where this "address already in use" error in the monitoring API comes from? Anything else using similar ports?

**Comment by xschlef** [comment]
our monitoring api uses port 3000 hardcoded. yours is using keystone port - 2000 which is 3000 as well. So changing the ports of your monitoring will fix this, or you merge your monitoring api with ours (seems cleaner)

**Comment by mpeuster** [comment]
mhm. I think it is a leftover from some other merges. I don't use the monitoring. ... The reason to not fix it to 3000 is that you might have multiple PoPs and thus multiple monitoring APIs running, right? ... However, I guess I found the main bug in b3b9c58  ... Tests work out now.

**Comment by xschlef** [comment]
The monitoring api querying always involve either a concrete docker container name or a datacenter + stack + vnf_name

that is why we fixed the port and only have one running instance.

**Comment by mpeuster** [comment]
Ok, but how do you ensure that it is not started multiple times? E.g. when I added the OpenStackApiEndpoint to multiple PoPs, the start method in openstack_api_endpoint.py is executed multiple times?!

**Comment by xschlef** [comment]
the first instance of the openstackapi endpoint will instantiate a singleton called manage.

all openstack endpoints have a reference to manage and manage has a reference to all of them.

manage instantiates the single instances we need. namely the chaining api and the monitoring api

**Comment by mpeuster** [comment]
Yeah, but this means the monitor line (25) of openstack_api_endpoint.py should completely be removed, right?

**Comment by xschlef** [comment]
yes line 25 should be removed!

**Comment by mpeuster** [comment]
Done. I think it was removed and I re-introduced it during the merge :D Sorry for that.

**Comment by xschlef** [comment]
I'm getting this error everytime I shutdown son-emu, also I can not instantiate new containers.

I have updated containernet as well as moved on to the newer docker-py version.
containernet>
INFO:root:stopping pushgateway container
Traceback (most recent call last):
  File "simple_heat_restapi.py", line 83, in <module>
    main()
  File "simple_heat_restapi.py", line 79, in main
    create_topology1()
  File "simple_heat_restapi.py", line 74, in create_topology1
    net.stop()
  File "/home/xschlef/sf_xschlef/son-emu/src/emuvim/dcemulator/net.py", line 290, in stop
    self.monitor_agent.stop()
  File "/home/xschlef/sf_xschlef/son-emu/src/emuvim/dcemulator/monitoring.py", line 520, in stop
    self._stop_container('pushgateway')
  File "/home/xschlef/sf_xschlef/son-emu/src/emuvim/dcemulator/monitoring.py", line 539, in _stop_container
    container.remove(force=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 259, in remove
    return self.client.api.remove_container(self.id, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 940, in remove_container
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 212, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.24/containers/e7cf408666af2b711fd9c2a8650abd26c037c217a2865774347dd656b99fbc49?force=True&link=False&v=False ("Unable to remove filesystem for e7cf408666af2b711fd9c2a8650abd26c037c217a2865774347dd656b99fbc49: remove /var/lib/docker/containers/e7cf408666af2b711fd9c2a8650abd26c037c217a2865774347dd656b99fbc49/shm: device or resource busy")

Also when running the unittests I'm getting an error in the monitoring api:
ERROR:root:emuvim.api.heat.openstack_dummies.monitoring_dummy_api: Error getting monitoring information.
 [Errno 2] No such file or directory: u'/sys/fs/cgroup/memory/docker/22256709946e682a10eceb920158e92c03ec40b4e564b64518832d8caee12b06/memory.usage_in_bytes'
Traceback (most recent call last):
  File "/home/xschlef/sf_xschlef/son-emu/src/emuvim/api/heat/openstack_dummies/monitoring_dummy_api.py", line 114, in get
    out_dict.update(DockerUtil.docker_mem(docker_id))
  File "/home/xschlef/sf_xschlef/son-emu/src/emuvim/api/heat/docker_util.py", line 93, in docker_mem
    out_dict['MEM_used'] = docker_mem_used(container_id)
  File "/home/xschlef/sf_xschlef/son-emu/src/emuvim/api/heat/docker_util.py", line 52, in docker_mem_used
    with open('/sys/fs/cgroup/memory/docker/' + container_id + '/memory.usage_in_bytes', 'r') as f:
IOError: [Errno 2] No such file or directory: u'/sys/fs/cgroup/memory/docker/22256709946e682a10eceb920158e92c03ec40b4e564b64518832d8caee12b06/memory.usage_in_bytes'


this suggests that I have missed a critical component to update, as travis is not picking up on this error.

**Comment by mpeuster** [comment]
The first error seems to be related to the monitoring implementation done by IMEC. Have you disabled the monitoring flag in your test topology? 

For example: `net = DCNetwork(controller=RemoteController, monitor=False, enable_learning=True)`?

The second error is strange. Don't have it on my dev machine and also not in travis. Not sure who of you is responsible for your monitoring implementation?

**Comment by mpeuster** [comment]
@xschlef Regarding the first error. How do you shutdown the emulator? It was not by typing exit, right?

**Comment by xschlef** [comment]
I shut it down with ctrl + d, so the equivalent of typing exit.

The second error is present in the main branch as well. This problem occurs because I am using debian that seems to use another structure for the docker cgroup. (maybe because kernel/systemd is older)

**Comment by xschlef** [comment]
I will merge this PR next week, so we can update our development VMs accordingly.

**Pull request merged**
